from app import predict

new_data = {
            'SK_ID_CURR': 285133,
            'NAME_CONTRACT_TYPE': 0,
            'FLAG_OWN_CAR': 1,
            'FLAG_OWN_REALTY': 1,
            'CNT_CHILDREN': 2,
            'AMT_INCOME_TOTAL': 405000.0,
            'AMT_CREDIT': 1971072.0,
            'AMT_ANNUITY': 68643.0,
            'AMT_GOODS_PRICE': 1800000.0,
            'REGION_POPULATION_RELATIVE': 0.006852,
            'DAYS_BIRTH_x': 13587,
            'DAYS_EMPLOYED': -1028.0,
            'DAYS_REGISTRATION': -7460.0,
            'DAYS_ID_PUBLISH': -1823,
            'OWN_CAR_AGE': 13.0,
            'FLAG_MOBIL': 1,
            'FLAG_EMP_PHONE': 1,
            'FLAG_WORK_PHONE': 0,
            'FLAG_CONT_MOBILE': 1,
            'FLAG_PHONE': 0,
            'FLAG_EMAIL': 0,
            'CNT_FAM_MEMBERS': 4.0,
            'REGION_RATING_CLIENT': 3,
            'REGION_RATING_CLIENT_W_CITY': 3,
            'HOUR_APPR_PROCESS_START': 11,
            'REG_REGION_NOT_LIVE_REGION': 0,
            'REG_REGION_NOT_WORK_REGION': 0,
            'LIVE_REGION_NOT_WORK_REGION': 0,
            'REG_CITY_NOT_LIVE_CITY': 0,
            'REG_CITY_NOT_WORK_CITY': 0,
            'LIVE_CITY_NOT_WORK_CITY': 0,
            'EXT_SOURCE_1_x': 0.6752425919070807,
            'EXT_SOURCE_2_x': 0.3277243436488533,
            'EXT_SOURCE_3_x': 0.6430255641096323,
            'APARTMENTS_AVG': 0.1227,
            'BASEMENTAREA_AVG': 0.0979,
            'YEARS_BEGINEXPLUATATION_AVG': 0.9841,
            'YEARS_BUILD_AVG': 0.7824,
            'COMMONAREA_AVG': 'nan',
            'ELEVATORS_AVG': 0.0,
            'ENTRANCES_AVG': 0.2414,
            'FLOORSMAX_AVG': 0.1667,
            'FLOORSMIN_AVG': 0.2083,
            'LANDAREA_AVG': 0.0,
            'LIVINGAPARTMENTS_AVG': 0.1,
            'LIVINGAREA_AVG': 0.1242,
            'NONLIVINGAPARTMENTS_AVG': 'nan',
            'NONLIVINGAREA_AVG': 0.0287,
            'APARTMENTS_MODE': 0.125,
            'BASEMENTAREA_MODE': 0.1016,
            'YEARS_BEGINEXPLUATATION_MODE': 0.9841,
            'YEARS_BUILD_MODE': 0.7909,
            'COMMONAREA_MODE': 'nan',
            'ELEVATORS_MODE': 0.0,
            'ENTRANCES_MODE': 0.2414,
            'FLOORSMAX_MODE': 0.1667,
            'FLOORSMIN_MODE': 0.2083,
            'LANDAREA_MODE': 0.0,
            'LIVINGAPARTMENTS_MODE': 0.1093,
            'LIVINGAREA_MODE': 0.1294,
            'NONLIVINGAPARTMENTS_MODE': 'nan',
            'NONLIVINGAREA_MODE': 0.0303,
            'APARTMENTS_MEDI': 0.1239,
            'BASEMENTAREA_MEDI': 0.0979,
            'YEARS_BEGINEXPLUATATION_MEDI': 0.9841,
            'YEARS_BUILD_MEDI': 0.7853,
            'COMMONAREA_MEDI': 'nan',
            'ELEVATORS_MEDI': 0.0,
            'ENTRANCES_MEDI': 0.2414,
            'FLOORSMAX_MEDI': 0.1667,
            'FLOORSMIN_MEDI': 0.2083,
            'LANDAREA_MEDI': 0.0,
            'LIVINGAPARTMENTS_MEDI': 0.1018,
            'LIVINGAREA_MEDI': 0.1265,
            'NONLIVINGAPARTMENTS_MEDI': 'nan',
            'NONLIVINGAREA_MEDI': 0.0293,
            'TOTALAREA_MODE': 0.1039,
            'OBS_30_CNT_SOCIAL_CIRCLE': 4.0,
            'DEF_30_CNT_SOCIAL_CIRCLE': 0.0,
            'OBS_60_CNT_SOCIAL_CIRCLE': 4.0,
            'DEF_60_CNT_SOCIAL_CIRCLE': 0.0,
            'DAYS_LAST_PHONE_CHANGE': -2169.0,
            'FLAG_DOCUMENT_2': 0,
            'FLAG_DOCUMENT_3': 1,
            'FLAG_DOCUMENT_4': 0,
            'FLAG_DOCUMENT_5': 0,
            'FLAG_DOCUMENT_6': 0,
            'FLAG_DOCUMENT_7': 0,
            'FLAG_DOCUMENT_8': 0,
            'FLAG_DOCUMENT_9': 0,
            'FLAG_DOCUMENT_10': 0,
            'FLAG_DOCUMENT_11': 0,
            'FLAG_DOCUMENT_12': 0,
            'FLAG_DOCUMENT_13': 0,
            'FLAG_DOCUMENT_14': 0,
            'FLAG_DOCUMENT_15': 0,
            'FLAG_DOCUMENT_16': 0,
            'FLAG_DOCUMENT_17': 0,
            'FLAG_DOCUMENT_18': 0,
            'FLAG_DOCUMENT_19': 0,
            'FLAG_DOCUMENT_20': 0,
            'FLAG_DOCUMENT_21': 0,
            'AMT_REQ_CREDIT_BUREAU_HOUR': 0.0,
            'AMT_REQ_CREDIT_BUREAU_DAY': 0.0,
            'AMT_REQ_CREDIT_BUREAU_WEEK': 0.0,
            'AMT_REQ_CREDIT_BUREAU_MON': 0.0,
            'AMT_REQ_CREDIT_BUREAU_QRT': 0.0,
            'AMT_REQ_CREDIT_BUREAU_YEAR': 0.0,
            'CODE_GENDER_F': True,
            'CODE_GENDER_M': False,
            'CODE_GENDER_XNA': False,
            'CODE_GENDER_nan': False,
            'NAME_TYPE_SUITE_Children': False,
            'NAME_TYPE_SUITE_Family': False,
            'NAME_TYPE_SUITE_Group of people': False,
            'NAME_TYPE_SUITE_Other_A': False,
            'NAME_TYPE_SUITE_Other_B': False,
            'NAME_TYPE_SUITE_Spouse, partner': False,
            'NAME_TYPE_SUITE_Unaccompanied': True,
            'NAME_TYPE_SUITE_nan': False,
            'NAME_INCOME_TYPE_Businessman': False,
            'NAME_INCOME_TYPE_Commercial associate': True,
            'NAME_INCOME_TYPE_Maternity leave': False,
            'NAME_INCOME_TYPE_Pensioner': False,
            'NAME_INCOME_TYPE_State servant': False,
            'NAME_INCOME_TYPE_Student': False,
            'NAME_INCOME_TYPE_Unemployed': False,
            'NAME_INCOME_TYPE_Working': False,
            'NAME_INCOME_TYPE_nan': False,
            'NAME_EDUCATION_TYPE_Academic degree': False,
            'NAME_EDUCATION_TYPE_Higher education': True,
            'NAME_EDUCATION_TYPE_Incomplete higher': False,
            'NAME_EDUCATION_TYPE_Lower secondary': False,
            'NAME_EDUCATION_TYPE_Secondary / secondary special': False,
            'NAME_EDUCATION_TYPE_nan': False,
            'NAME_FAMILY_STATUS_Civil marriage': False,
            'NAME_FAMILY_STATUS_Married': True,
            'NAME_FAMILY_STATUS_Separated': False,
            'NAME_FAMILY_STATUS_Single / not married': False,
            'NAME_FAMILY_STATUS_Unknown': False,
            'NAME_FAMILY_STATUS_Widow': False,
            'NAME_FAMILY_STATUS_nan': False,
            'NAME_HOUSING_TYPE_Co-op apartment': False,
            'NAME_HOUSING_TYPE_House / apartment': True,
            'NAME_HOUSING_TYPE_Municipal apartment': False,
            'NAME_HOUSING_TYPE_Office apartment': False,
            'NAME_HOUSING_TYPE_Rented apartment': False,
            'NAME_HOUSING_TYPE_With parents': False,
            'NAME_HOUSING_TYPE_nan': False,
            'OCCUPATION_TYPE_Accountants': True,
            'OCCUPATION_TYPE_Cleaning staff': False,
            'OCCUPATION_TYPE_Cooking staff': False,
            'OCCUPATION_TYPE_Core staff': False,
            'OCCUPATION_TYPE_Drivers': False,
            'OCCUPATION_TYPE_HR staff': False,
            'OCCUPATION_TYPE_High skill tech staff': False,
            'OCCUPATION_TYPE_IT staff': False,
            'OCCUPATION_TYPE_Laborers': False,
            'OCCUPATION_TYPE_Low-skill Laborers': False,
            'OCCUPATION_TYPE_Managers': False,
            'OCCUPATION_TYPE_Medicine staff': False,
            'OCCUPATION_TYPE_Private service staff': False,
            'OCCUPATION_TYPE_Realty agents': False,
            'OCCUPATION_TYPE_Sales staff': False,
            'OCCUPATION_TYPE_Secretaries': False,
            'OCCUPATION_TYPE_Security staff': False,
            'OCCUPATION_TYPE_Waiters/barmen staff': False,
            'OCCUPATION_TYPE_nan': False,
            'WEEKDAY_APPR_PROCESS_START_FRIDAY': False,
            'WEEKDAY_APPR_PROCESS_START_MONDAY': False,
            'WEEKDAY_APPR_PROCESS_START_SATURDAY': True,
            'WEEKDAY_APPR_PROCESS_START_SUNDAY': False,
            'WEEKDAY_APPR_PROCESS_START_THURSDAY': False,
            'WEEKDAY_APPR_PROCESS_START_TUESDAY': False,
            'WEEKDAY_APPR_PROCESS_START_WEDNESDAY': False,
            'WEEKDAY_APPR_PROCESS_START_nan': False,
            'ORGANIZATION_TYPE_Advertising': False,
            'ORGANIZATION_TYPE_Agriculture': False,
             'ORGANIZATION_TYPE_Bank': False,
             'ORGANIZATION_TYPE_Business Entity Type 1': False,
             'ORGANIZATION_TYPE_Business Entity Type 2': False,
             'ORGANIZATION_TYPE_Business Entity Type 3': False,
             'ORGANIZATION_TYPE_Cleaning': False,
             'ORGANIZATION_TYPE_Construction': False,
             'ORGANIZATION_TYPE_Culture': False,
             'ORGANIZATION_TYPE_Electricity': False,
             'ORGANIZATION_TYPE_Emergency': False,
             'ORGANIZATION_TYPE_Government': False,
             'ORGANIZATION_TYPE_Hotel': False,
             'ORGANIZATION_TYPE_Housing': False,
             'ORGANIZATION_TYPE_Industry: type 1': False,
             'ORGANIZATION_TYPE_Industry: type 10': False,
             'ORGANIZATION_TYPE_Industry: type 11': False,
             'ORGANIZATION_TYPE_Industry: type 12': False,
             'ORGANIZATION_TYPE_Industry: type 13': False,
             'ORGANIZATION_TYPE_Industry: type 2': False,
             'ORGANIZATION_TYPE_Industry: type 3': False,
             'ORGANIZATION_TYPE_Industry: type 4': False,
             'ORGANIZATION_TYPE_Industry: type 5': False,
             'ORGANIZATION_TYPE_Industry: type 6': False,
             'ORGANIZATION_TYPE_Industry: type 7': False,
             'ORGANIZATION_TYPE_Industry: type 8': False,
             'ORGANIZATION_TYPE_Industry: type 9': False,
             'ORGANIZATION_TYPE_Insurance': False,
             'ORGANIZATION_TYPE_Kindergarten': False,
             'ORGANIZATION_TYPE_Legal Services': False,
             'ORGANIZATION_TYPE_Medicine': False,
             'ORGANIZATION_TYPE_Military': False,
             'ORGANIZATION_TYPE_Mobile': False,
             'ORGANIZATION_TYPE_Other': False,
             'ORGANIZATION_TYPE_Police': False,
             'ORGANIZATION_TYPE_Postal': False,
             'ORGANIZATION_TYPE_Realtor': False,
             'ORGANIZATION_TYPE_Religion': False,
             'ORGANIZATION_TYPE_Restaurant': False,
             'ORGANIZATION_TYPE_School': False,
             'ORGANIZATION_TYPE_Security': False,
             'ORGANIZATION_TYPE_Security Ministries': False,
             'ORGANIZATION_TYPE_Self-employed': True,
             'ORGANIZATION_TYPE_Services': False,
             'ORGANIZATION_TYPE_Telecom': False,
             'ORGANIZATION_TYPE_Trade: type 1': False,
             'ORGANIZATION_TYPE_Trade: type 2': False,
             'ORGANIZATION_TYPE_Trade: type 3': False,
             'ORGANIZATION_TYPE_Trade: type 4': False,
             'ORGANIZATION_TYPE_Trade: type 5': False,
             'ORGANIZATION_TYPE_Trade: type 6': False,
             'ORGANIZATION_TYPE_Trade: type 7': False,
             'ORGANIZATION_TYPE_Transport: type 1': False,
             'ORGANIZATION_TYPE_Transport: type 2': False,
             'ORGANIZATION_TYPE_Transport: type 3': False,
             'ORGANIZATION_TYPE_Transport: type 4': False,
             'ORGANIZATION_TYPE_University': False,
             'ORGANIZATION_TYPE_XNA': False,
             'ORGANIZATION_TYPE_nan': False,
             'FONDKAPREMONT_MODE_not specified': False,
             'FONDKAPREMONT_MODE_org spec account': False,
             'FONDKAPREMONT_MODE_reg oper account': True,
             'FONDKAPREMONT_MODE_reg oper spec account': False,
             'FONDKAPREMONT_MODE_nan': False,
             'HOUSETYPE_MODE_block of flats': True,
             'HOUSETYPE_MODE_specific housing': False,
             'HOUSETYPE_MODE_terraced house': False,
             'HOUSETYPE_MODE_nan': False,
             'WALLSMATERIAL_MODE_Block': False,
             'WALLSMATERIAL_MODE_Mixed': False,
             'WALLSMATERIAL_MODE_Monolithic': False,
             'WALLSMATERIAL_MODE_Others': False,
             'WALLSMATERIAL_MODE_Panel': False,
             'WALLSMATERIAL_MODE_Stone, brick': True,
             'WALLSMATERIAL_MODE_Wooden': False,
             'WALLSMATERIAL_MODE_nan': False,
             'EMERGENCYSTATE_MODE_No': True,
             'EMERGENCYSTATE_MODE_Yes': False,
             'EMERGENCYSTATE_MODE_nan': False,
             'DAYS_EMPLOYED_ANOM': False,
             'DAYS_EMPLOYED_PERC': -0.0756605578862147,
             'INCOME_CREDIT_PERC': 0.2054719462302747,
             'INCOME_PER_PERSON': 101250.0,
             'ANNUITY_INCOME_PERC': 0.1694888888888888,
             'PAYMENT_RATE': 0.0348252118644067,
             '1': 1.0,
             'EXT_SOURCE_1_y': 0.6752425919070807,
             'EXT_SOURCE_2_y': 0.3277243436488533,
             'EXT_SOURCE_3_y': 0.6430255641096323,
             'DAYS_BIRTH_y': 13587.0,
             'EXT_SOURCE_1^2': 0.4559525579253923,
             'EXT_SOURCE_1 EXT_SOURCE_2': 0.2212934352364985,
             'EXT_SOURCE_1 EXT_SOURCE_3': 0.4341982485719008,
             'EXT_SOURCE_1 DAYS_BIRTH': 9174.521096241506,
             'EXT_SOURCE_2^2': 0.1074032454200716,
             'EXT_SOURCE_2 EXT_SOURCE_3': 0.2107351309472628,
             'EXT_SOURCE_2 DAYS_BIRTH': 4452.790657156969,
             'EXT_SOURCE_3^2': 0.4134818760985108,
             'EXT_SOURCE_3 DAYS_BIRTH': 8736.788339557574,
             'DAYS_BIRTH^2': 184606569.0,
             'EXT_SOURCE_1^3': 0.3078785870002052,
             'EXT_SOURCE_1^2 EXT_SOURCE_2': 0.1494267527811149,
             'EXT_SOURCE_1^2 EXT_SOURCE_3': 0.2931891507672052,
             'EXT_SOURCE_1^2 DAYS_BIRTH': 6195.027404532306,
             'EXT_SOURCE_1 EXT_SOURCE_2^2': 0.0725232458166815,
             'EXT_SOURCE_1 EXT_SOURCE_2 EXT_SOURCE_3': 0.1422973360267078,
             'EXT_SOURCE_1 EXT_SOURCE_2 DAYS_BIRTH': 3006.713904558305,
             'EXT_SOURCE_1 EXT_SOURCE_3^2': 0.2792005737233609,
             'EXT_SOURCE_1 EXT_SOURCE_3 DAYS_BIRTH': 5899.451603346416,
             'EXT_SOURCE_1 DAYS_BIRTH^2': 124654218.13463332,
             'EXT_SOURCE_2^3': 0.0351986581110497,
             'EXT_SOURCE_2^2 EXT_SOURCE_3': 0.0690630324734468,
             'EXT_SOURCE_2^2 DAYS_BIRTH': 1459.2878955225135,
             'EXT_SOURCE_2 EXT_SOURCE_3^2': 0.1355080764550809,
             'EXT_SOURCE_2 EXT_SOURCE_3 DAYS_BIRTH': 2863.2582241804603,
             'EXT_SOURCE_2 DAYS_BIRTH^2': 60500066.65879174,
             'EXT_SOURCE_3^3': 0.265879416627354,
             'EXT_SOURCE_3^2 DAYS_BIRTH': 5617.978250550466,
             'EXT_SOURCE_3 DAYS_BIRTH^2': 118706743.16956876,
             'DAYS_BIRTH^3': 2508249453003.0,
             'DAYS_CREDIT': -846.75,
             'CREDIT_DAY_OVERDUE': 0.0,
             'DAYS_CREDIT_ENDDATE': 51.0,
             'DAYS_ENDDATE_FACT': -554.0,
             'AMT_CREDIT_MAX_OVERDUE': 0.0,
             'CNT_CREDIT_PROLONG': 0.0,
             'AMT_CREDIT_SUM': 535317.795,
             'AMT_CREDIT_SUM_DEBT': 297855.0,
             'AMT_CREDIT_SUM_LIMIT': 0.0,
             'AMT_CREDIT_SUM_OVERDUE': 0.0,
             'DAYS_CREDIT_UPDATE': -281.75,
             'MONTHS_BALANCE': 0.0,
             'CREDIT_ACTIVE_Active': True,
             'CREDIT_ACTIVE_Bad debt': False,
             'CREDIT_ACTIVE_Closed': False,
             'CREDIT_ACTIVE_Sold': False,
             'CREDIT_ACTIVE_nan': False,
             'CREDIT_CURRENCY_currency 1': True,
             'CREDIT_CURRENCY_currency 2': False,
             'CREDIT_CURRENCY_currency 3': False,
             'CREDIT_CURRENCY_nan': False,
             'CREDIT_TYPE_Another type of loan': False,
             'CREDIT_TYPE_Car loan': False,
             'CREDIT_TYPE_Cash loan (non-earmarked)': False,
             'CREDIT_TYPE_Consumer credit': True,
             'CREDIT_TYPE_Credit card': False,
             'CREDIT_TYPE_Loan for business development': False,
             'CREDIT_TYPE_Loan for the purchase of equipment': False,
             'CREDIT_TYPE_Loan for working capital replenishment': False,
             'CREDIT_TYPE_Microloan': False,
             'CREDIT_TYPE_Mortgage': False,
             'CREDIT_TYPE_Real estate loan': False,
             'CREDIT_TYPE_Unknown type of loan': False,
             'CREDIT_TYPE_nan': False,
             'STATUS_0': True,
             'STATUS_1': False,
             'STATUS_2': False,
             'STATUS_3': False,
             'STATUS_5': False,
             'STATUS_C': False,
             'STATUS_X': False,
             'STATUS_nan': False,
             'AMT_APPLICATION': 51610.5,
             'AMT_DOWN_PAYMENT': 5175.0,
             'NFLAG_LAST_APPL_IN_DAY': 1.0,
             'RATE_DOWN_PAYMENT': 0.1002685569974017,
             'RATE_INTEREST_PRIMARY': 'nan',
             'RATE_INTEREST_PRIVILEGED': 'nan',
             'DAYS_DECISION': -2169.0,
             'SELLERPLACE_AREA': 86.0,
             'CNT_PAYMENT': 12.0,
             'DAYS_FIRST_DRAWING': 'nan',
             'DAYS_FIRST_DUE': -2138.0,
             'DAYS_LAST_DUE_1ST_VERSION': -1808.0,
             'DAYS_LAST_DUE': -1808.0,
             'DAYS_TERMINATION': -1805.0,
             'NFLAG_INSURED_ON_APPROVAL': 0.0,
             'APP_CREDIT_PERC': 1.0112864826734855,
             'NAME_CONTRACT_TYPE_Cash loans': False,
             'NAME_CONTRACT_TYPE_Consumer loans': True,
             'NAME_CONTRACT_TYPE_Revolving loans': False,
             'NAME_CONTRACT_TYPE_XNA': False,
             'NAME_CONTRACT_TYPE_nan': False,
             'FLAG_LAST_APPL_PER_CONTRACT_N': False,
             'FLAG_LAST_APPL_PER_CONTRACT_Y': True,
             'FLAG_LAST_APPL_PER_CONTRACT_nan': False,
             'NAME_CASH_LOAN_PURPOSE_Building a house or an annex': False,
             'NAME_CASH_LOAN_PURPOSE_Business development': False,
             'NAME_CASH_LOAN_PURPOSE_Buying a garage': False,
             'NAME_CASH_LOAN_PURPOSE_Buying a holiday home / land': False,
             'NAME_CASH_LOAN_PURPOSE_Buying a home': False,
             'NAME_CASH_LOAN_PURPOSE_Buying a new car': False,
             'NAME_CASH_LOAN_PURPOSE_Buying a used car': False,
             'NAME_CASH_LOAN_PURPOSE_Car repairs': False,
             'NAME_CASH_LOAN_PURPOSE_Education': False,
             'NAME_CASH_LOAN_PURPOSE_Everyday expenses': False,
             'NAME_CASH_LOAN_PURPOSE_Furniture': False,
             'NAME_CASH_LOAN_PURPOSE_Gasification / water supply': False,
             'NAME_CASH_LOAN_PURPOSE_Hobby': False,
             'NAME_CASH_LOAN_PURPOSE_Journey': False,
             'NAME_CASH_LOAN_PURPOSE_Medicine': False,
             'NAME_CASH_LOAN_PURPOSE_Money for a third person': False,
             'NAME_CASH_LOAN_PURPOSE_Other': False,
             'NAME_CASH_LOAN_PURPOSE_Payments on other loans': False,
             'NAME_CASH_LOAN_PURPOSE_Purchase of electronic equipment': False,
             'NAME_CASH_LOAN_PURPOSE_Refusal to name the goal': False,
             'NAME_CASH_LOAN_PURPOSE_Repairs': False,
             'NAME_CASH_LOAN_PURPOSE_Urgent needs': False,
             'NAME_CASH_LOAN_PURPOSE_Wedding / gift / holiday': False,
             'NAME_CASH_LOAN_PURPOSE_XAP': True,
             'NAME_CASH_LOAN_PURPOSE_XNA': False,
             'NAME_CASH_LOAN_PURPOSE_nan': False,
             'NAME_CONTRACT_STATUS_Approved': True,
             'NAME_CONTRACT_STATUS_Canceled': False,
             'NAME_CONTRACT_STATUS_Refused': False,
             'NAME_CONTRACT_STATUS_Unused offer': False,
             'NAME_CONTRACT_STATUS_nan': False,
             'NAME_PAYMENT_TYPE_Cash through the bank': True,
             'NAME_PAYMENT_TYPE_Cashless from the account of the employer': False,
             'NAME_PAYMENT_TYPE_Non-cash from your account': False,
             'NAME_PAYMENT_TYPE_XNA': False,
             'NAME_PAYMENT_TYPE_nan': False,
             'CODE_REJECT_REASON_CLIENT': False,
             'CODE_REJECT_REASON_HC': False,
             'CODE_REJECT_REASON_LIMIT': False,
             'CODE_REJECT_REASON_SCO': False,
             'CODE_REJECT_REASON_SCOFR': False,
             'CODE_REJECT_REASON_SYSTEM': False,
             'CODE_REJECT_REASON_VERIF': False,
             'CODE_REJECT_REASON_XAP': True,
             'CODE_REJECT_REASON_XNA': False,
             'CODE_REJECT_REASON_nan': False,
             'NAME_CLIENT_TYPE_New': True,
             'NAME_CLIENT_TYPE_Refreshed': False,
             'NAME_CLIENT_TYPE_Repeater': False,
             'NAME_CLIENT_TYPE_XNA': False,
             'NAME_CLIENT_TYPE_nan': False,
             'NAME_GOODS_CATEGORY_Additional Service': False,
             'NAME_GOODS_CATEGORY_Audio/Video': False,
             'NAME_GOODS_CATEGORY_Auto Accessories': False,
             'NAME_GOODS_CATEGORY_Clothing and Accessories': False,
             'NAME_GOODS_CATEGORY_Computers': False,
             'NAME_GOODS_CATEGORY_Construction Materials': False,
             'NAME_GOODS_CATEGORY_Consumer Electronics': False,
             'NAME_GOODS_CATEGORY_Direct Sales': False,
             'NAME_GOODS_CATEGORY_Education': False,
             'NAME_GOODS_CATEGORY_Fitness': False,
             'NAME_GOODS_CATEGORY_Furniture': False,
             'NAME_GOODS_CATEGORY_Gardening': False,
             'NAME_GOODS_CATEGORY_Homewares': False,
             'NAME_GOODS_CATEGORY_Insurance': False,
             'NAME_GOODS_CATEGORY_Jewelry': False,
             'NAME_GOODS_CATEGORY_Medical Supplies': False,
             'NAME_GOODS_CATEGORY_Medicine': False,
             'NAME_GOODS_CATEGORY_Mobile': False,
             'NAME_GOODS_CATEGORY_Office Appliances': False,
             'NAME_GOODS_CATEGORY_Other': False,
             'NAME_GOODS_CATEGORY_Photo / Cinema Equipment': True,
             'NAME_GOODS_CATEGORY_Sport and Leisure': False,
             'NAME_GOODS_CATEGORY_Tourism': False,
             'NAME_GOODS_CATEGORY_Vehicles': False,
             'NAME_GOODS_CATEGORY_Weapon': False,
             'NAME_GOODS_CATEGORY_XNA': False,
             'NAME_GOODS_CATEGORY_nan': False,
             'NAME_PORTFOLIO_Cards': False,
             'NAME_PORTFOLIO_Cars': False,
             'NAME_PORTFOLIO_Cash': False,
             'NAME_PORTFOLIO_POS': True,
             'NAME_PORTFOLIO_XNA': False,
             'NAME_PORTFOLIO_nan': False,
             'NAME_PRODUCT_TYPE_XNA': True,
             'NAME_PRODUCT_TYPE_walk-in': False,
             'NAME_PRODUCT_TYPE_x-sell': False,
             'NAME_PRODUCT_TYPE_nan': False,
             'CHANNEL_TYPE_AP+ (Cash loan)': False,
             'CHANNEL_TYPE_Car dealer': False,
             'CHANNEL_TYPE_Channel of corporate sales': False,
             'CHANNEL_TYPE_Contact center': False,
             'CHANNEL_TYPE_Country-wide': True,
             'CHANNEL_TYPE_Credit and cash offices': False,
             'CHANNEL_TYPE_Regional / Local': False,
             'CHANNEL_TYPE_Stone': False,
             'CHANNEL_TYPE_nan': False,
             'NAME_SELLER_INDUSTRY_Auto technology': False,
             'NAME_SELLER_INDUSTRY_Clothing': False,
             'NAME_SELLER_INDUSTRY_Connectivity': True,
             'NAME_SELLER_INDUSTRY_Construction': False,
             'NAME_SELLER_INDUSTRY_Consumer electronics': False,
             'NAME_SELLER_INDUSTRY_Furniture': False,
             'NAME_SELLER_INDUSTRY_Industry': False,
             'NAME_SELLER_INDUSTRY_Jewelry': False,
             'NAME_SELLER_INDUSTRY_MLM partners': False,
             'NAME_SELLER_INDUSTRY_Tourism': False,
             'NAME_SELLER_INDUSTRY_XNA': False,
             'NAME_SELLER_INDUSTRY_nan': False,
             'NAME_YIELD_GROUP_XNA': False,
             'NAME_YIELD_GROUP_high': True,
             'NAME_YIELD_GROUP_low_action': False,
             'NAME_YIELD_GROUP_low_normal': False,
             'NAME_YIELD_GROUP_middle': False,
             'NAME_YIELD_GROUP_nan': False,
             'PRODUCT_COMBINATION_Card Street': False,
             'PRODUCT_COMBINATION_Card X-Sell': False,
             'PRODUCT_COMBINATION_Cash': False,
             'PRODUCT_COMBINATION_Cash Street: high': False,
             'PRODUCT_COMBINATION_Cash Street: low': False,
             'PRODUCT_COMBINATION_Cash Street: middle': False,
             'PRODUCT_COMBINATION_Cash X-Sell: high': False,
             'PRODUCT_COMBINATION_Cash X-Sell: low': False,
             'PRODUCT_COMBINATION_Cash X-Sell: middle': False,
             'PRODUCT_COMBINATION_POS household with interest': False,
             'PRODUCT_COMBINATION_POS household without interest': False,
             'PRODUCT_COMBINATION_POS industry with interest': False,
             'PRODUCT_COMBINATION_POS industry without interest': False,
             'PRODUCT_COMBINATION_POS mobile with interest': True,
             'PRODUCT_COMBINATION_POS mobile without interest': False,
             'PRODUCT_COMBINATION_POS other with interest': False,
             'PRODUCT_COMBINATION_POS others without interest': False,
             'PRODUCT_COMBINATION_nan': False,
             'CNT_INSTALMENT': 12.0,
             'CNT_INSTALMENT_FUTURE': 6.0,
             'SK_DPD': 0.0,
             'SK_DPD_DEF': 0.0,
             'NAME_CONTRACT_STATUS_Active': True,
             'NAME_CONTRACT_STATUS_Amortized debt': False,
             'NAME_CONTRACT_STATUS_Completed': False,
             'NAME_CONTRACT_STATUS_Demand': False,
             'NAME_CONTRACT_STATUS_Returned to the store': False,
             'NAME_CONTRACT_STATUS_Signed': False,
             'NUM_INSTALMENT_VERSION': 1.0,
             'NUM_INSTALMENT_NUMBER': 6.5,
             'DAYS_INSTALMENT': -1973.0,
             'DAYS_ENTRY_PAYMENT': -1985.75,
             'AMT_INSTALMENT': 5914.27875,
             'AMT_PAYMENT': 5914.27875,
             'PAYMENT_PERC': 1.0,
             'PAYMENT_DIFF': 0.0,
             'DPD': 0.0,
             'DBD': 12.75,
             'AMT_BALANCE': 'nan',
             'AMT_CREDIT_LIMIT_ACTUAL': 'nan',
             'AMT_DRAWINGS_ATM_CURRENT': 'nan',
             'AMT_DRAWINGS_CURRENT': 'nan',
             'AMT_DRAWINGS_OTHER_CURRENT': 'nan',
             'AMT_DRAWINGS_POS_CURRENT': 'nan',
             'AMT_INST_MIN_REGULARITY': 'nan',
             'AMT_PAYMENT_CURRENT': 'nan',
             'AMT_PAYMENT_TOTAL_CURRENT': 'nan',
             'AMT_RECEIVABLE_PRINCIPAL': 'nan',
             'AMT_RECIVABLE': 'nan',
             'AMT_TOTAL_RECEIVABLE': 'nan',
             'CNT_DRAWINGS_ATM_CURRENT': 'nan',
             'CNT_DRAWINGS_CURRENT': 'nan',
             'CNT_DRAWINGS_OTHER_CURRENT': 'nan',
             'CNT_DRAWINGS_POS_CURRENT': 'nan',
             'CNT_INSTALMENT_MATURE_CUM': 'nan',
             'CC_COUNT': 'nan'
             }

def test_predict():
    prediction = predict(new_data)
    assert prediction == 'Accepté'